name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  jest:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm test -- --coverage

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: jest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

#      - name: Build and push Docker image
#        run: |
#          docker buildx build . \
#            --platform linux/amd64,linux/arm64 \
#            -t tggl/tggl-proxy:2.1.2 \
#            -t tggl/tggl-proxy:latest \
#            --push

      - name: Publish README to Docker Hub
        run: |
          curl -X PATCH \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.DOCKER_PASSWORD }}" \
            -d '{"description": "Tggl Proxy to self-host", "full_description": "'"$(<README.md)"'"}' \
            https://hub.docker.com/v2/repositories/tggl/tggl-proxy/
